POST https://tkbutsuribu-git-bbs-tokokitabutsuris-projects.vercel.app/api/bbs_post HTTP/1.1
Content-Type: application/json

{
    "poster_name":"name",
    "comment":"aaaaaa>>12345 asdfa\naa",
    "thread_id":123,
}