name: deploy preview website
on: 
  push: 
    branches: 
      - '**'
      - '!main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          alias-domains: tkbutsuribu-{{BRANCH}}.vercel.app
#https://github.com/marketplace/actions/vercel-action
